name: Build Gitleaks

on:
  schedule:
    - cron: '0 9 * * 1'
    # for debug
#     - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build Gitleaks
      run: |
        git clone https://github.com/gitleaks/gitleaks.git
        cd gitleaks
        make build
    - name: Commit and push if changed
      run: |
        git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/~
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add gitleaks
        git commit -m "Add built gitleaks binary" || exit 0
        git push
