name: Build Gitleaks

on:
  schedule:
    - cron: '0 9 * * 1'
    # for debug
#     - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build Gitleaks
      run: |
        git clone https://github.com/gitleaks/gitleaks.git
        mkdir bin
        cd gitleaks
        make build
        cp gitleaks ../bin/  
        
    - name: Commit and push if changed
      run: |
        git config core.filemode false
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull --rebase
        git add -f bin/gitleaks
        git commit -m "Add built gitleaks binary" || exit 0
        git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{github.ref}}
